apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: python-wheels-example
spec:
  build:
    useBuildKit: true
    secrets:
      - GITHUB_USER
      - GITHUB_TOKEN
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web-app
      src: ./webapp
      dockerfileName: Dockerfile.using-public-wheel-in-gh-package
      ports:
        - name: http
          port: 8000
      publicPort: http

