FROM docker.io/python:3.9.21-alpine3.21

WORKDIR /app
# Install the wheel. Get GitHUb user and token from secrets GITHUB_USER and GITHUB_TOKEN
RUN pip install --upgrade pip
RUN --mount=type=secret,id=GITHUB_USER,dst=/secrets/github-user.txt \
    --mount=type=secret,id=GITHUB_TOKEN,dst=/secrets/github-token.txt \
    echo "Installing wheel from private GitHub package" && \
    pip install https://$(cat /secrets/github-user.txt):$(cat /secrets/github-token.txt)@github.com/satr/python-wheels-example/releases/download/v0.1.0/simple_webapp-0.1.0-py3-none-any.whl > /dev/null 2>&1 && \
    echo "Wheel installed successfully"

EXPOSE 8000
USER 1000

# Run app
CMD ["uvicorn", "simple_webapp.main:app", "--host", "0.0.0.0", "--port", "8000"]
